In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("datasetforpreprocessing.csv")

In [3]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [5]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [6]:
from sklearn.impute import SimpleImputer
s=SimpleImputer(missing_values=np.nan,strategy="mean")
x[:,1:3]=s.fit_transform(x[:,1:3])

In [7]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x[:,1:3]=sc.fit_transform(x[:,1:3])

In [9]:
x

array([['France', 0.758874361590019, 0.7494732544921677],
       ['Spain', -1.7115038793306814, -1.4381784072687531],
       ['Germany', -1.2755547779917342, -0.8912654918285229],
       ['Spain', -0.1130238410878753, -0.253200423814921],
       ['Germany', 0.17760889313808945, 6.632191985654332e-16],
       ['France', -0.5489729424268225, -0.5266568815350361],
       ['Spain', 0.0, -1.0735697969752662],
       ['France', 1.3401398300419485, 1.3875383225057696],
       ['Germany', 1.6307725642679132, 1.7521469327992565],
       ['France', -0.2583402082008577, 0.29371249162530916]], dtype=object)

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [30]:
x

array([[0.0, 1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [1.0, 0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [1.0, 0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [1.0, 0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [1.0, 0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [0.0, 1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [1.0, 0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [0.0, 1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [1.0, 0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [0.0, 1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

In [23]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [31]:
import statsmodels.api as sm
x_opt=np.array(x[:,[0,1,2,3,4,5]],dtype=float)
model=sm.OLS(endog=y,exog=x_opt).fit()
model.summary()

C:\Users\damar\anaconda3\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.289
Model:                            OLS   Adj. R-squared:                 -0.280
Method:                 Least Squares   F-statistic:                    0.5079
Date:                Mon, 10 Aug 2020   Prob (F-statistic):              0.734
Time:                        15:32:36   Log-Likelihood:                -5.5530
No. Observations:                  10   AIC:                             21.11
Df Residuals:                       5   BIC:                             22.62
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.2107      0.175      1.204      0.283      -0.239       0.661
x2             0.7759      0.333      2.332      0.067      -0.079       1.631
x3             0.1330      0.303      0.439      0.679      -0.645       0.911
x4             0.0777      0.342      0.227      0.829      -0.801       0.957
x5            -0.3056      0.523     -0.585      0.584      -1.649       1.038
x6             0.1529      0.603      0.254      0.810      -1.397       1.703
==============================================================================
Omnibus:                        0.258   Durbin-Watson:                   2.399
Prob(Omnibus):                  0.879   Jarque-Bera (JB):                0.405
Skew:                          -0.026   Prob(JB):                        0.817
Kurtosis:                       2.016   Cond. No.                     2.10e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.68e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [32]:
x_1=x[:,1:]
x_1

array([[1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

In [37]:
const=np.ones((10,1)).astype(int)
const

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [38]:
x_1 = np.append(arr = const, values = x_1,axis = 1)
print(x_1)

[[1 1.0 0.0 0.0 0.758874361590019 0.7494732544921677]
 [1 0.0 0.0 1.0 -1.7115038793306814 -1.4381784072687531]
 [1 0.0 1.0 0.0 -1.2755547779917342 -0.8912654918285229]
 [1 0.0 0.0 1.0 -0.1130238410878753 -0.253200423814921]
 [1 0.0 1.0 0.0 0.17760889313808945 6.632191985654332e-16]
 [1 1.0 0.0 0.0 -0.5489729424268225 -0.5266568815350361]
 [1 0.0 0.0 1.0 0.0 -1.0735697969752662]
 [1 1.0 0.0 0.0 1.3401398300419485 1.3875383225057696]
 [1 0.0 1.0 0.0 1.6307725642679132 1.7521469327992565]
 [1 1.0 0.0 0.0 -0.2583402082008577 0.29371249162530916]]


In [39]:
x_opt = np.array(x_1[:,[0,1,2,4,5]],dtype = float)
model = sm.OLS(endog =y, exog = x_opt).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.289
Model:                            OLS   Adj. R-squared:                 -0.280
Method:                 Least Squares   F-statistic:                    0.5079
Date:                Mon, 10 Aug 2020   Prob (F-statistic):              0.734
Time:                        15:43:16   Log-Likelihood:                -5.5530
No. Observations:                  10   AIC:                             21.11
Df Residuals:                       5   BIC:                             22.62
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2884      0.451      0.639      0.551      -0.872       1.448
x1             0.4874      0.633      0.770      0.476      -1.139       2.114
x2             0.0553      0.622      0.089      0.933      -1.543       1.653
x3            -0.3056      0.523     -0.585      0.584      -1.649       1.038
x4             0.1529      0.603      0.254      0.810      -1.397       1.703
==============================================================================
Omnibus:                        0.258   Durbin-Watson:                   2.399
Prob(Omnibus):                  0.879   Jarque-Bera (JB):                0.405
Skew:                          -0.026   Prob(JB):                        0.817
Kurtosis:                       2.016   Cond. No.                         8.03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [41]:
x_opt=np.array(x_1[:,[0,1,3,4,5]],dtype=float)
model=sm.OLS(endog=y,exog=x_opt).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.289
Model:                            OLS   Adj. R-squared:                 -0.280
Method:                 Least Squares   F-statistic:                    0.5079
Date:                Mon, 10 Aug 2020   Prob (F-statistic):              0.734
Time:                        15:45:46   Log-Likelihood:                -5.5530
No. Observations:                  10   AIC:                             21.11
Df Residuals:                       5   BIC:                             22.62
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3437      0.357      0.962      0.380      -0.574       1.262
x1             0.4322      0.459      0.943      0.389      -0.747       1.611
x2            -0.0553      0.622     -0.089      0.933      -1.653       1.543
x3            -0.3056      0.523     -0.585      0.584      -1.649       1.038
x4             0.1529      0.603      0.254      0.810      -1.397       1.703
==============================================================================
Omnibus:                        0.258   Durbin-Watson:                   2.399
Prob(Omnibus):                  0.879   Jarque-Bera (JB):                0.405
Skew:                          -0.026   Prob(JB):                        0.817
Kurtosis:                       2.016   Cond. No.                         6.75
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [42]:
x_opt=np.array(x_1[:,[0,1,3,4]],dtype=float)
model=sm.OLS(endog=y,exog=x_opt).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.280
Model:                            OLS   Adj. R-squared:                 -0.080
Method:                 Least Squares   F-statistic:                    0.7769
Date:                Mon, 10 Aug 2020   Prob (F-statistic):              0.548
Time:                        15:48:40   Log-Likelihood:                -5.6169
No. Observations:                  10   AIC:                             19.23
Df Residuals:                       6   BIC:                             20.44
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3660      0.318      1.151      0.294      -0.412       1.144
x1             0.4434      0.419      1.057      0.331      -0.583       1.469
x2            -0.1444      0.471     -0.306      0.770      -1.298       1.009
x3            -0.1837      0.189     -0.971      0.369      -0.647       0.279
==============================================================================
Omnibus:                        0.533   Durbin-Watson:                   2.518
Prob(Omnibus):                  0.766   Jarque-Bera (JB):                0.509
Skew:                          -0.077   Prob(JB):                        0.775
Kurtosis:                       1.906   Cond. No.                         3.99
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [43]:
x_opt=np.array(x_1[:,[0,1,3]],dtype=float)
model=sm.OLS(endog=y,exog=x_opt).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.167
Model:                            OLS   Adj. R-squared:                 -0.071
Method:                 Least Squares   F-statistic:                    0.7000
Date:                Mon, 10 Aug 2020   Prob (F-statistic):              0.528
Time:                        15:50:47   Log-Likelihood:                -6.3463
No. Observations:                  10   AIC:                             18.69
Df Residuals:                       7   BIC:                             19.60
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3333      0.315      1.058      0.325      -0.411       1.078
x1             0.4167      0.417      1.000      0.351      -0.569       1.402
x2          1.249e-16      0.445    2.8e-16      1.000      -1.053       1.053
==============================================================================
Omnibus:                        0.977   Durbin-Watson:                   2.660
Prob(Omnibus):                  0.614   Jarque-Bera (JB):                0.629
Skew:                           0.073   Prob(JB):                        0.730
Kurtosis:                       1.780   Cond. No.                         3.93
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [44]:
x_opt=np.array(x_1[:,[0,1]],dtype=float)
model=sm.OLS(endog=y,exog=x_opt).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.167
Model:                            OLS   Adj. R-squared:                  0.063
Method:                 Least Squares   F-statistic:                     1.600
Date:                Mon, 10 Aug 2020   Prob (F-statistic):              0.242
Time:                        15:51:54   Log-Likelihood:                -6.3463
No. Observations:                  10   AIC:                             16.69
Df Residuals:                       8   BIC:                             17.30
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3333      0.208      1.600      0.148      -0.147       0.814
x1             0.4167      0.329      1.265      0.242      -0.343       1.176
==============================================================================
Omnibus:                        0.977   Durbin-Watson:                   2.660
Prob(Omnibus):                  0.614   Jarque-Bera (JB):                0.629
Skew:                           0.073   Prob(JB):                        0.730
Kurtosis:                       1.780   Cond. No.                         2.45
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [45]:
x_opt=np.array(x_1[:,0],dtype=float)
model=sm.OLS(endog=y,exog=x_opt).fit()
model.summary()

C:\Users\damar\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\damar\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\damar\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Mon, 10 Aug 2020   Prob (F-statistic):                nan
Time:                        15:52:34   Log-Likelihood:                -7.2579
No. Observations:                  10   AIC:                             16.52
Df Residuals:                       9   BIC:                             16.82
Df Model:                           0                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5000      0.167      3.000      0.015       0.123       0.877
==============================================================================
Omnibus:                       13.263   Durbin-Watson:                   2.800
Prob(Omnibus):                  0.001   Jarque-Bera (JB):                1.667
Skew:                           0.000   Prob(JB):                        0.435
Kurtosis:                       1.000   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [49]:
from sklearn.model_selection import train_test_split
x_tr,x_te,y_tr,y_te=train_test_split(x,y,test_size=0.2,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_tr,y_tr)
y_pred=lr.predict(x_te)


In [48]:
from sklearn.metrics import r2_score,mean_squared_error
r2=r2_score(y_te,y_pred)
r2

0.0